import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import AuthProvider from "./context/AuthProvider"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isDev = process.env.NODE_ENV === 'development'
  return (
    <html lang="en" suppressHydrationWarning={isDev}>
      <body className={inter.className} >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
